### ISSUE TITLE
Simple log severity detection

### ISSUE THREAD

**Issue by SzymonSt** [SzymonSt/docker-signalone#67]

**Comment by Kranium2002** [comment]
Why don't we make severity a part of the json that our web agent outputs? We can do this until we get enough data of our own to finetune a model. What are your thoughts?

**Comment by SzymonSt** [comment]
honestly I think it is too much, simple regex is enough. Let's not overload lms with inference context.

**Comment by Kranium2002** [comment]
How do you propose we predict the severity of a error using regex? Do we assume that the log output consists of severity?

**Comment by SzymonSt** [comment]
This actually works on two levels:
 1. We don't just go through containers logs we also check the container state on agent site, so if container exited with level different that 0 it is already critical
 2. We assume there is log level noun different for different systems(warn, warning, error, panic, Exception etc.)

this is what I have in mind

**Comment by SzymonSt** [comment]
Of course in future we would like to have more advanced classification, but it is not needed for our current MVP
