### ISSUE TITLE
fix analysis engine output bugs

### ISSUE THREAD

**Issue by SzymonSt** [SzymonSt/docker-signalone#96]
Each bug/minor unwanted hallucination should be a separate comment, if resolved comment should be deleted.

Output analysis checklist:

- [ ]  Is most important infomration included in the log summary
- [ ]  Is there any information incorrect about the analyzed log tail?
- [ ]  Are steps/solutions provided by service mostly correct 
- [ ] Summarization and proposed solutions guide user step be step through issue troubleshooting process
- [ ]  where there any severe hallucinations like: [
 1. Harmful executable commands
 2. Proposal of usage of outdated frameworks/libraries
]

**Comment by SzymonSt** [comment]
### Bug 1
Description: Part of log summary is being generated within the title 


![Image](https://github.com/SzymonSt/docker-signalone/assets/48925621/ebbbc9b8-cf39-4362-a56d-86f273dfbf5a)

**Comment by SzymonSt** [comment]
### Bug 2
Description: LLM should use 'websearch' tool not tell user to use it.


![Image](https://github.com/SzymonSt/docker-signalone/assets/48925621/7cd21cec-3a21-4936-aa90-f930db4fe322)

**Comment by SzymonSt** [comment]
### Bug 3 
Description: We would rather direct user to the specific articles, questions, docs than web searches: 

![Image](https://github.com/SzymonSt/docker-signalone/assets/48925621/4fcaee48-2af6-495f-8dcb-6513b31a116f)

**Comment by SzymonSt** [comment]
### Bug 4
Description: Undesired explainability action from the model:

![Image](https://github.com/SzymonSt/docker-signalone/assets/48925621/afbdf489-bf4e-4da8-b38d-a24f6bd18711)

**Comment by SzymonSt** [comment]
### Bug 5 
Description: Mediation is not what interests our users while using signa0ne :P 


![Image](https://github.com/SzymonSt/docker-signalone/assets/48925621/bdd9de7d-5a1b-4c62-96a9-1d21b89bd177)

**Comment by SzymonSt** [comment]
### Bug 6 
Description: hallucinated sources


![Image](https://github.com/SzymonSt/docker-signalone/assets/48925621/4fad6c96-412c-4d4d-8caf-34698934cefa)

**Comment by Kranium2002** [comment]
![Image](https://github.com/SzymonSt/docker-signalone/assets/74452705/ab349681-de32-4123-afda-386871f4218f)

I was testing the current code and the output contains stuff like:

Remember, do not assume anything that is not there in the intermediate steps, and give a proper answer. Do not output any code or commands if not confirmed by the intermediate steps, and do not prompt users to search anything in the web or ask for support.

**Comment by SzymonSt** [comment]
tavily returns some bullshit unrelated to topic

![Image](https://github.com/SzymonSt/docker-signalone/assets/48925621/c28d8b56-047f-4d52-ad17-8186f864ed76)
